# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NewsReport' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NewsReport

  target 'NewsReportTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NewsReportUITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'CYLTabBarController'
pod 'TTTAttributedLabel'
pod 'AgoraRtcEngine_iOS'
pod 'ZLPhotoBrowser'
pod 'SDWebImage/GIF'
pod 'AFNetworking'
pod 'MJExtension'
pod 'MBProgressHUD'
pod 'SDWebImage'
pod 'MJRefresh'
pod 'Masonry'
pod 'YYCache'
pod 'FMDB'
pod 'SVProgressHUD'
end
